"""Pure configuration helpers for Family DEFCON.

This module intentionally has no Home Assistant imports so its validation and
migration behavior can be tested without starting Home Assistant.
"""

from __future__ import annotations

from datetime import time
import hashlib
import hmac
import re
import secrets
from typing import Any
from urllib.parse import urlparse

CONFIG_ENTRY_VERSION = 6
INTEGRATION_VERSION = "2.0.0b1"

PEOPLE_SLOTS = 8
STATION_SLOTS = 8
PIN_LENGTH = 4
# Dashboard verification may check up to eight people in sequence. This modest
# work factor keeps a full invalid-PIN scan responsive while still avoiding the
# effectively uncosted SHA256 hashes used by earlier releases.
PIN_HASH_ITERATIONS = 20_000
# Accept hashes generated by the earlier 120,000-iteration beta, but reject
# larger imported work factors that could stall an eight-person PIN scan.
MAX_PIN_HASH_ITERATIONS = 120_000

DEFAULT_PEOPLE = ["Parent 1", "Parent 2", "Child 1", "Child 2", "Child 3"]
DEFAULT_ROLES = {
    "Parent 1": "parent",
    "Parent 2": "parent",
    "Child 1": "child",
    "Child 2": "child",
    "Child 3": "child",
}
DEFAULT_CHILD_TARGETS = ["Child 1", "Child 2", "Child 3"]
DEFAULT_PARENT_TARGETS = ["Parent 1", "Parent 2"]
DEFAULT_STATION = {
    "id": "dashboard",
    "name": "Home Assistant Dashboard",
    "enabled": True,
    "key_entity": "",
}


def default_options(
    *,
    cooldown_seconds: int = 30,
    dns_enabled: bool = True,
    adguard_base_url: str = "",
) -> dict[str, Any]:
    """Return a new complete set of options for a UI-created entry."""
    return {
        "use_ui_config": True,
        "cooldown_seconds": int(cooldown_seconds),
        "people_list": list(DEFAULT_PEOPLE),
        "people_roles": dict(DEFAULT_ROLES),
        "people_pins": {},
        "people_pin_hashes": {},
        "people_adguard_clients": {name: name for name in DEFAULT_PEOPLE},
        "default_targets_list": list(DEFAULT_CHILD_TARGETS),
        "parent_targets_list": list(DEFAULT_PARENT_TARGETS),
        "dashboard_targets_list": list(DEFAULT_CHILD_TARGETS + DEFAULT_PARENT_TARGETS),
        "dashboard_station_id": "dashboard",
        "dashboard_default_target": "Child 1",
        "stations_list": [dict(DEFAULT_STATION)],
        "dns_enabled": bool(dns_enabled),
        "adguard_use_ha_integration": True,
        "adguard_base_url": normalize_adguard_url(adguard_base_url),
        "enforcement_mode": "active",
        "mutual_destruction_scope": "default_targets",
        "adguard_username_secret": "adguard_username",
        "adguard_password_secret": "adguard_password",
        "adguard_rule_prefix": "Family DEFCON Block",
        "use_advanced_yaml_overrides": False,
        "people_yaml": "",
        "auth_users_yaml": "",
        "stations_yaml": "",
        "adguard_clients_yaml": "",
        "penalties_yaml": "",
        "launches_before_mutual_destruction": 5,
        "chain_before_mutual_destruction": 4,
        "daily_reset_time": "05:00:00",
        "max_event_log": 25,
        "allow_parent_targets_default": False,
        "require_station_match": False,
        "require_key_for_launch": False,
        "pin_timeout_seconds": 60,
        "max_bad_pin_attempts": 3,
        "lockout_seconds_after_bad_pins": 120,
        "first_strike_target_minutes": 30,
        "retaliator_extra_minutes": 15,
        "retaliation_target_minutes": 30,
        "reattacker_extra_minutes": 15,
        "reattack_target_minutes": 45,
    }


def slugify_identifier(value: str) -> str:
    """Return the stable slug used by generated person entities."""
    slug = re.sub(r"[^a-z0-9_]+", "_", str(value).strip().lower())
    return re.sub(r"_+", "_", slug).strip("_")


def hash_pin_value(
    pin: str,
    *,
    salt: str | None = None,
    iterations: int = PIN_HASH_ITERATIONS,
) -> str:
    """Return a salted PBKDF2-SHA256 hash for a local dashboard PIN."""
    actual_iterations = int(iterations)
    if not 1 <= actual_iterations <= MAX_PIN_HASH_ITERATIONS:
        raise ValueError("PIN hash iterations are outside the supported range")
    actual_salt = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac(
        "sha256",
        str(pin).encode(),
        actual_salt.encode(),
        actual_iterations,
    ).hex()
    return f"pbkdf2_sha256${actual_iterations}${actual_salt}${digest}"


def verify_pin_value(pin: str, user_data: dict[str, Any]) -> bool:
    """Verify current PBKDF2, older SHA256, or legacy plaintext PINs."""
    if not str(pin):
        return False

    stored_hash = str(user_data.get("pin_hash", "") or "")
    if stored_hash:
        try:
            parts = stored_hash.split("$")
            algorithm = parts[0]

            if algorithm == "sha256" and len(parts) == 3:
                _, salt, expected = parts
                digest = hashlib.sha256(f"{salt}:{pin}".encode()).hexdigest()
                return hmac.compare_digest(digest, expected)

            if algorithm == "pbkdf2_sha256" and len(parts) == 4:
                _, iterations_raw, salt, expected = parts
                iterations = int(iterations_raw)
                if not 1 <= iterations <= MAX_PIN_HASH_ITERATIONS:
                    return False
                digest = hashlib.pbkdf2_hmac(
                    "sha256",
                    str(pin).encode(),
                    salt.encode(),
                    iterations,
                ).hex()
                return hmac.compare_digest(digest, expected)
        except (TypeError, ValueError):
            return False
        return False

    legacy_pin = str(user_data.get("pin", "") or "")
    return bool(legacy_pin) and hmac.compare_digest(legacy_pin, str(pin))


def migrate_auth_users_mapping(auth_users: dict[str, Any]) -> dict[str, Any]:
    """Replace plaintext PINs in an auth users mapping with hashes."""
    migrated: dict[str, Any] = {}
    for person, raw_user in auth_users.items():
        if not isinstance(raw_user, dict):
            migrated[str(person)] = raw_user
            continue

        user = dict(raw_user)
        plain_pin = str(user.pop("pin", "") or "")
        if plain_pin and not str(user.get("pin_hash", "") or ""):
            user["pin_hash"] = hash_pin_value(plain_pin)
        migrated[str(person)] = user
    return migrated


def normalize_adguard_url(raw_url: Any) -> str:
    """Normalize an optional AdGuard URL and reject unsafe or invalid values."""
    value = str(raw_url or "").strip()
    if not value:
        return ""
    if "://" not in value:
        value = f"http://{value}"

    parsed = urlparse(value)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError("invalid AdGuard URL")
    try:
        parsed.port
    except ValueError as err:
        raise ValueError("invalid AdGuard port") from err
    if not parsed.hostname or any(character.isspace() for character in parsed.netloc):
        raise ValueError("invalid AdGuard host")
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise ValueError(
            "AdGuard URL must not contain credentials, a query, or a fragment"
        )

    path = parsed.path.rstrip("/")
    if path == "/control":
        path = ""
    elif path:
        raise ValueError("AdGuard URL must not contain a path")

    return f"{parsed.scheme}://{parsed.netloc}{path}"


def normalize_daily_reset_time(raw_value: Any) -> str:
    """Return a Home Assistant time selector value with seconds."""
    if isinstance(raw_value, time):
        parsed = raw_value
    else:
        parsed = time.fromisoformat(str(raw_value or "").strip())
    return parsed.replace(microsecond=0).isoformat()


def validate_people_input(user_input: dict[str, Any]) -> dict[str, str]:
    """Return field and base errors for the guided people form."""
    errors: dict[str, str] = {}
    names: dict[str, str] = {}
    slugs: dict[str, str] = {}
    configured_count = 0
    dashboard_target_count = 0

    for index in range(1, PEOPLE_SLOTS + 1):
        prefix = f"person_{index}"
        name_field = f"{prefix}_name"
        pin_field = f"{prefix}_pin"
        name = str(user_input.get(name_field, "") or "").strip()
        pin = str(user_input.get(pin_field, "") or "").strip()

        if pin and not name:
            errors[name_field] = "person_name_required"
        if pin and (len(pin) != PIN_LENGTH or not pin.isascii() or not pin.isdigit()):
            errors[pin_field] = "invalid_pin"
        if not name:
            continue

        configured_count += 1
        lowered = name.casefold()
        slug = slugify_identifier(name)
        if lowered in names:
            errors[name_field] = "duplicate_person"
        else:
            names[lowered] = name_field
        if not slug and name_field not in errors:
            errors[name_field] = "invalid_person_name"
        elif slug in slugs and name_field not in errors:
            errors[name_field] = "duplicate_person_identifier"
        else:
            slugs[slug] = name_field

        if bool(user_input.get(f"{prefix}_dashboard_target", False)):
            dashboard_target_count += 1

    if configured_count == 0:
        errors["base"] = "people_required"
    elif dashboard_target_count == 0:
        errors["base"] = "dashboard_target_required"
    return errors


def build_people_options(
    user_input: dict[str, Any],
    existing: dict[str, Any],
) -> dict[str, Any]:
    """Build guided people options while preserving write-only PIN hashes."""
    updated = dict(existing)
    previous_people = existing.get("people_list", [])
    if not isinstance(previous_people, list):
        previous_people = []
    previous_hashes = existing.get("people_pin_hashes", {})
    if not isinstance(previous_hashes, dict):
        previous_hashes = {}
    legacy_pins = existing.get("people_pins", {})
    if not isinstance(legacy_pins, dict):
        legacy_pins = {}

    people: list[str] = []
    roles: dict[str, str] = {}
    pin_hashes: dict[str, str] = {}
    clients: dict[str, str] = {}
    default_targets: list[str] = []
    parent_targets: list[str] = []
    dashboard_targets: list[str] = []

    for index in range(1, PEOPLE_SLOTS + 1):
        prefix = f"person_{index}"
        name = str(user_input.get(f"{prefix}_name", "") or "").strip()
        if not name:
            continue

        old_name = (
            str(previous_people[index - 1]) if index <= len(previous_people) else ""
        )
        people.append(name)
        roles[name] = str(user_input.get(f"{prefix}_role", "child") or "child")

        new_pin = str(user_input.get(f"{prefix}_pin", "") or "").strip()
        clear_pin = bool(user_input.get(f"{prefix}_clear_pin", False))
        if clear_pin:
            pass
        elif new_pin:
            pin_hashes[name] = hash_pin_value(new_pin)
        elif name in previous_hashes:
            pin_hashes[name] = str(previous_hashes[name])
        elif old_name in previous_hashes:
            pin_hashes[name] = str(previous_hashes[old_name])
        elif name in legacy_pins and str(legacy_pins[name]):
            pin_hashes[name] = hash_pin_value(str(legacy_pins[name]))
        elif old_name in legacy_pins and str(legacy_pins[old_name]):
            pin_hashes[name] = hash_pin_value(str(legacy_pins[old_name]))

        clients[name] = (
            str(user_input.get(f"{prefix}_adguard_client", "") or name).strip() or name
        )
        if bool(user_input.get(f"{prefix}_default_target", False)):
            default_targets.append(name)
        if bool(user_input.get(f"{prefix}_parent_target", False)):
            parent_targets.append(name)
        if bool(user_input.get(f"{prefix}_dashboard_target", False)):
            dashboard_targets.append(name)

    current_default = str(existing.get("dashboard_default_target", "") or "")
    if current_default not in dashboard_targets:
        current_default = next(
            (name for name in default_targets if name in dashboard_targets),
            dashboard_targets[0] if dashboard_targets else "",
        )

    updated.update(
        {
            "people_list": people,
            "people_roles": roles,
            "people_pins": {},
            "people_pin_hashes": pin_hashes,
            "people_adguard_clients": clients,
            "default_targets_list": default_targets,
            "parent_targets_list": parent_targets,
            "dashboard_targets_list": dashboard_targets,
            "dashboard_default_target": current_default,
        }
    )
    return updated


def validate_station_input(user_input: dict[str, Any]) -> dict[str, str]:
    """Return field and base errors for the guided station form."""
    errors: dict[str, str] = {}
    station_ids: dict[str, str] = {}

    for index in range(1, STATION_SLOTS + 1):
        field = f"station_{index}_id"
        station_id = str(user_input.get(field, "") or "").strip()
        if not station_id:
            continue
        lowered = station_id.casefold()
        if lowered in station_ids:
            errors[field] = "duplicate_station"
        else:
            station_ids[lowered] = station_id

    if not station_ids:
        errors["base"] = "station_required"
        return errors

    dashboard_station = str(user_input.get("dashboard_station_id", "") or "").strip()
    if dashboard_station.casefold() not in station_ids:
        errors["dashboard_station_id"] = "unknown_station"
    return errors


def build_station_options(
    user_input: dict[str, Any],
    existing: dict[str, Any],
) -> dict[str, Any]:
    """Build validated station and dashboard options."""
    updated = dict(existing)
    stations: list[dict[str, Any]] = []
    station_ids: dict[str, str] = {}
    for index in range(1, STATION_SLOTS + 1):
        prefix = f"station_{index}"
        station_id = str(user_input.get(f"{prefix}_id", "") or "").strip()
        if not station_id:
            continue
        station_ids[station_id.casefold()] = station_id
        stations.append(
            {
                "id": station_id,
                "name": str(user_input.get(f"{prefix}_name", "") or station_id).strip()
                or station_id,
                "enabled": bool(user_input.get(f"{prefix}_enabled", True)),
                "key_entity": str(
                    user_input.get(f"{prefix}_key_entity", "") or ""
                ).strip(),
            }
        )

    dashboard_station = str(user_input.get("dashboard_station_id", "") or "").strip()
    updated["stations_list"] = stations
    updated["dashboard_station_id"] = station_ids.get(
        dashboard_station.casefold(), dashboard_station
    )

    dashboard_targets = existing.get("dashboard_targets_list", [])
    if not isinstance(dashboard_targets, list):
        dashboard_targets = []
    requested_target = str(user_input.get("dashboard_default_target", "") or "").strip()
    updated["dashboard_default_target"] = (
        requested_target
        if requested_target in dashboard_targets
        else (str(dashboard_targets[0]) if dashboard_targets else "")
    )
    return updated
